version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: release-v1.19.x
  ignore:
  - dependency-name: k8s.io/*
    versions:
    - ">0.19.0"
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target_branch: master
  ignore:
  - dependency-name: k8s.io/*
    versions:
    - ">0.20.0"
